### ISSUE TITLE
Crashes when exiting app

### ISSUE THREAD

**Issue by rixwoodling** [xMasterX/unleashed-extra-pack#108]
Uart Terminal crashes 100% when exiting app via menu.
1. open app
2. use return button to exit
3. notice crash

Error reads:
Flipper crashed and was rebooted
furi_check failed

v1.4 uart
fw 0.102.3 (28-05-2024)
happens on previous versions as well

**Comment by xMasterX** [comment]
crash is fixed but app is not updated in catalog yet, I will update manifests soon

**Comment by xMasterX** [comment]
updated manifests, will be updated in catalog today maybe, all should work after that
