### ISSUE TITLE
NfcMaker is broken

### ISSUE THREAD

**Issue by RekordNadoev** [xMasterX/unleashed-extra-pack#12]
Due to firmware changes, NfcMaker application no longer compiling:

- lib/toolbox/random_name.c removed from firmware tree
- lib/toolbox/random_name.h removed from firmware tree
- NFC_APP_EXTENSION variable renamed to NFC_APP_FILENAME_EXTENSION

If one puts the files to the firmware tree and changes variable name in app's sources, app won't start with "Error. Load failed. NFC/nfc_maker.fap. Found unsatisfied imports"

**Comment by xMasterX** [comment]
fixed in dev

**Comment by RekordNadoev** [comment]
I've forgotten something important...

Thank you Unleashed firmware developers!!! :-)
