### ISSUE TITLE
universal remote: feature request: priorities worked one

### ISSUE THREAD

**Issue by nanderer** [xMasterX/unleashed-extra-pack#15]
It would be grate if when the bar runs through you could press a button just after it worked and then it starts at that position but backwards the next time to be much faster. Also a way to fine tune to a specific tv by pressing stol and than forwards, backwards one step, then thats it if it workes and then it goes only one this with a single press before switching back to universal again...

Thanks in advance

**Comment by xMasterX** [comment]
what universal remote you are talking about? there is none in that repo
