### ISSUE TITLE
universal remote: missing elements tv

### ISSUE THREAD

**Issue by nanderer** [xMasterX/unleashed-extra-pack#16]
Hi,

Its missing my cheap Chinese tv branded with elements. Maybe you could include it:
https://flpr.app/sf#path=infrared/ElementsTV.ir&key=iEzearNdxWz-nKal596Iww&id=VVbh7E

Thanks

**Comment by nanderer** [comment]
Why is there no no upload button in the mobile version @GitHub?

And now i have to zip it to ;(

[ElementsTV.ir.zip](https://github.com/xMasterX/all-the-plugins/files/12653506/ElementsTV.ir.zip)

There you (finally) go. Consider switching to a real open source git platform (like bitbucletorgitlab)

**Comment by xMasterX** [comment]
> There you (finally) go. Consider switching to a real open source git platform (like bitbucletorgitlab)

no

**Comment by xMasterX** [comment]
Create issue in correct repo

**Comment by nanderer** [comment]
Plese tell me where
