### ISSUE TITLE
Enhanced sub-ghz chat not booting

### ISSUE THREAD

**Issue by Chilinwithmyflipper** [xMasterX/unleashed-extra-pack#162]
I downloaded the enchanced sub-ghz chat and my flipper just kept crashing and said "NULL pointer dereference" i know it said expect bugs it the description but I can't open open the application!

**Comment by xMasterX** [comment]
your firmware version and app build? 
where you downloaded the app?
do you use external radio module or internal only?

**Comment by JuanLassoVelasco** [comment]
Hey, I'm having the same issue. 
My firmware version is the recently distributed 1.0.1 official release.
I downloaded the app from the new app catalog on the flipper zero mobile app.
The app version it displays there is the 1.1 version.

**Comment by JuanLassoVelasco** [comment]
I'm also using the internal radio module.

**Comment by xMasterX** [comment]
I was able to reproduce the issue on the release, but it works fine on dev
There is an RC coming and next release on the way, app will not be fixed for older release since 1.0.1 had memory managment issues, wait for the next release or try Release Candidate version if its ready

**Comment by xMasterX** [comment]
Official fw release is out, update and update the app in companion app, then try again, all should be fine
