### ISSUE TITLE
POCSAG readme refers to a non-existent example config file

### ISSUE THREAD

**Issue by m-b-m** [xMasterX/unleashed-extra-pack#39]
The [POCSAG README](https://github.com/xMasterX/all-the-plugins/blob/dev/base_pack/pocsag_pager/README.md) reads:

> To add new presets and frequencies create file - yourMicroSD/pocsag/settings.txt
And put THIS - https://github.com/flipperdevices/flipperzero-firmware/blob/dev/assets/resources/subghz/assets/setting_user.example file contents into it, and edit this example for yourself, add needed frequencies

The link leads to a 404

Please improve the documentation so that syntax and/or a working example config file is available. Thanks!

**Comment by xMasterX** [comment]
done
