### ISSUE TITLE
Bluetooth apps tell me to update my firmware

### ISSUE THREAD

**Issue by noiob** [xMasterX/unleashed-extra-pack#58]
running the current stable firmware (0.98.2) both bad_bt and ble_spam won't start and instead show a MissingImports error

![Screenshot-20240212-163731](https://github.com/xMasterX/all-the-plugins/assets/8197071/fb5c5f8f-33ce-4f2f-b040-200f8503febd)

**Comment by xMasterX** [comment]
those apps are not working with official firmware
builds in releases sections are for Unleashed firmware only
which means they are working fine only on UL
if you are using other firmware you need to build sources yourself

for OFW i recommend using official flipper apps catalogue
all apps in catalogue are verified, fixed, and working well with official API
