### ISSUE TITLE
Pomodoro active countdown?

### ISSUE THREAD

**Issue by ajtran303** [xMasterX/unleashed-extra-pack#8]
Should the Pomodoro timer be actively counting down?

When I start the timer, it doesn't update in real time like I would expect a clock app to.

Instead, it updates when I click a button..

What do you think about this?

**Comment by xMasterX** [comment]
Issue appears only when app is started from favourites, this is related to same issue that was fixed in bunch of other plugins
Will be fixed and pushed in next batch update into catalog, thanks for info

**Comment by xMasterX** [comment]
fixed in dev, not published yet to catalog, will be updated in catalog soon
