### ISSUE TITLE
UART Terminal not sending carriage return.

### ISSUE THREAD

**Issue by BetaVVolf** [xMasterX/unleashed-extra-pack#87]
The UART terminal app only sends a carriage return character when you send an AT command, regular commands just input the text and change to the terminal output screen with the command hanging there. Eg, inputting commands to a micropython instance running on an ESP32, works when using the AT keyboard, but not using the regular keyboard or quick commands.

**Comment by xMasterX** [comment]
Hi, I added new option in Setup menu, in new version you can select what mode to use for regular Send command
Newline or CRLF
AT command shortcut will be using CRLF in any case

Will be in next unleashed dev build and release and source already updated in this repo
