### ISSUE TITLE
flipper-dcf77 LED indication bug

### ISSUE THREAD

**Issue by mxcdoam** [xMasterX/unleashed-extra-pack#88]
When this app is running it makes LED indicator to blink with orange light. If the led light is on and the app is exited with a "back" button - led indicator stays on until another app will use indicator. 

To reproduce:
1. Open the app
2. Wait until the LED lights up
3. Press back button to get to the homescreen. The LED indicator continue to be on.

**Comment by xMasterX** [comment]
fixed, thanks for report

**Comment by xMasterX** [comment]
fixed, thanks for report
